### ISSUE TITLE
Plan for releasing the rendering code

### ISSUE THREAD

**Issue by lxxue** [Stanford-TML/circle_dataset#1]
Hi,

Thanks for the great work. I wonder if you have any plans to release the code for the rendering in Habitat or Blender? I would like to try to render some sequences as well.

**Comment by jaraujo98** [comment]
Hello @lxxue,

thank you for your interest in CIRCLE! I am working on getting that code ready for release. You may expect it later this week.

**Comment by lxxue** [comment]
Sounds great, thank you!

**Comment by jaraujo98** [comment]
@lxxue code is posted. Let me know if you run into any issues.
