### ISSUE TITLE
Upload the modified scene glb file

### ISSUE THREAD

**Issue by lxxue** [Stanford-TML/circle_dataset#2]
Hi Joao,

Thank you for releasing the code so quickly. 

I tried to recreate the modified glb file with blender (right click the `openings` version and `Delete Hierarchy`). My Blender 3.4.1/3.5.0 on Ubuntu 20.04 crashed and my Blender 3.3.1 on Mac had issues exporting the modified glb file with the following error:

![image](https://user-images.githubusercontent.com/22346567/232891996-4b2bcabd-1f05-47e8-acba-e9402897fb79.png)

I wonder if you can share the modified glb file? Thank you.

**Comment by jaraujo98** [comment]
Ah, yes, I ran into this too using Blender 3.3. Thanks for the catch! Version 3.0 worked, so this is probably a bug they introduced recently. I'll report it to them. In the meantime, you can find the modified `glb` [here](https://circledataset.s3.us-west-2.amazonaws.com/release/102815835-no-doors.glb).
