### ISSUE TITLE
How do you split the CIRCLE dataset?

### ISSUE THREAD

**Issue by anitacen** [Stanford-TML/circle_dataset#4]
Hi, I am wondering how do you split the CIRCLE dataset into train and test split?

**Comment by jaraujo98** [comment]
Hello @anitacen,

thank you for your interest in CIRCLE. We used three splitting strategies in our experiments:

1. Random splitting: 85/15% split of sequences at random for training and testing, respectively.
2. Task splitting: A task is start region/goal region pair (such as `kitchen2_hutch_2_kitchen2`). I have attached the list of tasks we used for training and testing (when I say we used a task, I mean we used all the sequences for that task; the split between training and testing is again 85/15).
3. Scene splitting: We trained on the sequences captured on all scenes except for the ones captured in the media room and the closet, which were used for testing (which resulted in a 70/30 train and test split).

If you have any further questions please let me know.

[circle_split_by_task.json](https://github.com/Stanford-TML/circle_dataset/files/13854566/circle_split_by_task.json)

**Comment by anitacen** [comment]
Thanks for your reply!
